### ISSUE TITLE
Include NIDM version in JSON metadata

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm-query#9]
Could we also include the NIDM-\* version associated with a given query? 

While we should as much as possible insure backward compatibility, I think that it's good practice to keep a track of the version against which a given query can run. 

Another suggestion by @satra (at the Chicago NIDASH meeting), is that we could check for the NIDM version as part of each query.

(As an example, the contrast query has changed between [NIDM-Results 0.2.0](https://github.com/incf-nidash/nidm/blob/NIDM0.2.0/nidm/nidm-results/query/get_contrasts.rq) and [NIDM-Results 1.1.0](https://github.com/incf-nidash/nidm/blob/NIDM-Results_1.1.0/nidm/nidm-results/query/get_contrasts.rq).)

**Comment by nicholsn** [comment]
Really good idea. Are you thinking that we include "version" as additional metadata in the query json file? Is the nidm version included in the nidm-results ttl file (i.e., are you saying that the actual queries should check for a version?

**Comment by cmaumet** [comment]
I was thinking of adding the version as a metadata but the query itself could also check for the NIDM version. In NIDM-Results, the nidm version is available as an attribute of the overall bundle, cf. for example [SPM example 001](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/spm/example001/example001_spm_results.ttl#L371).

**Comment by vsoch** [comment]
@nicholsn and @cmaumet - just wanted to give you a quick note that I've been paused on this because I'm writing my thesis this week - I'm almost done and should be able to put all these issues/fixes together this weekend!

**Comment by nicholsn** [comment]
writing a thesis in a week!? Impressive and no big rush - we could also
take a look at what needs to be done :-)

**Comment by vsoch** [comment]
Nope I just finished as much as I can do for now... will get to this soon!

**Comment by vsoch** [comment]
Ok, so a quick question. I'm concerned about this because a user generating a query may not have a clue what NIDM version he/she is generating for. Is there even a programmatic way to get it? What about if we store the nidm version as a variable somewhere in the API, and if the user does not know (and does not specify) we assume it's for the current version?

**Comment by vsoch** [comment]
Ok, version is added!

**Comment by cmaumet** [comment]
Thank you @vsoch! Just a quick comment: if someone is writing a query, he/she must have some knowledge about the model (e.g. by reading the spec or by looking at an example document...) and therefore should know the corresponding NIDM version. Hope that makes sense!
